# concept_keywords.py

CONCEPT_KEYWORDS = {
    "harappan": "Harappan Civilization",
    "indus": "Indus Valley Civilization",
    "vedic": "Vedic Period",
    "ashokan": "Ashokan Edicts",
    "mauryan": "Mauryan Empire",
    "gupta": "Gupta Empire",
    "tank": "Revenue and Land Systems",
    "temple": "Temple-based Education",
    "brahmin": "Brahmadeya and Village Institutions",
    "science": "History of Indian Science",
    "mathematics": "Ancient Indian Mathematics",
    "surgery": "Ancient Indian Medicine",
    "rock-cut": "Archaeological Sites",
    "terracotta": "Material Culture",
    "copper": "Chalcolithic Cultures",
    "burzahom": "Burzahom Site",
    "chandraketugarh": "Terracotta Art",
    "ganeshwar": "Copper Artifacts",
    "eripatti": "Land Revenue Systems",
    "taniyurs": "Village Donations",
    "ghatikas": "Education in Temples",
    "guild": "Ancient Indian Economy",
    "shrenis": "Ancient Indian Economy",
    "dholavira": "Water Management Systems",
    "chanhudaro": "Harappan Sites",
    "kot diji": "Harappan Sites",
    "sohgaura": "Ancient Sites",
    "aryadeva": "Jaina Scholar",
    "dignaga": "Buddhist Scholar",
    "nathamuni": "Vaishnava Scholar",
    "bhavabhuti": "Playwright",
    "hastimalla": "Playwright",
    "kshemeshvara": "Playwright",
    "panini": "Ancient Linguistics",
    "amarasimha": "Ancient Lexicographer",
    "kalidasa": "Classical Sanskrit Literature",
    "yuan chwang": "Chinese Traveller",
    "hiuen tsang": "Chinese Traveller",
    "pushyabhutis": "Post-Gupta Kingdoms",
    "maukharis": "Post-Gupta Kingdoms",
    "maitrakas": "Post-Gupta Kingdoms",
    "kautilya": "Arthashastra",
    "vishti": "Forced Labour",
    "southeast asia": "Maritime Trade",
    "bay of bengal": "Maritime Trade",
    "bhavabhuti": "Ancient Literature",
    "shramaṇa": "Religious Orders",
    "parivraajaka": "Religious Orders",
    "agrahaarika": "Religious Orders",
    "magadha": "Magadha Region",
    "usa": "US Debt Default and Faith-backed Debt",
    "treasury": "US Treasury Bonds",
    "syndicate": "Syndicated Lending and Risk Sharing",
    "digitalrupee": "Sovereign Digital Currency in India",
    "rbi": "RBI Balance Sheet and Monetary Policy",
    "landrecords": "Digital Land Records Modernisation Programme",
    "cadastral": "Digitisation of Cadastral Maps",
    "rights": "Transliteration of Land Rights Records",
    "nbfc": "Liquidity Adjustment Facility and NBFCs",
    "foreigninvestors": "FIIs and Indian Government Securities",
    "stockexchange": "Debt Platforms on Stock Exchanges",
    "corporatebonds": "Corporate Bonds and Government Securities",
    "insurance": "Insurance and Pension Funds in Bond Markets",
    "financial": "Financial Instruments in the Economy",
    "sectors": "Economic Sectors Classification",
    "capital": "Physical and Working Capital Examples",
    "foreignbanks": "Regulations for Foreign Banks in India",
    "csr": "CSR Expenditure and Rules in India",
    "cblo": "Collateral Borrowing and Lending Obligations",
    "invit": "InvITs Taxation and Borrowing Status",
    "interestrates": "Central Bank Interest Rates and Inflation",
    "sterilization": "RBI's Sterilization Operations",
    "markets": "Indian Financial Markets Overview",
    "smallfarmer": "Small Farmer Large Field Concept",
    "niger": "Niger Cultivation and Usage",
    "intangible": "Intangible vs Tangible Investments",
    "pli": "Production Linked Incentive Scheme",
    "msme": "MSME Definitions and Priority Sector Lending",
    "priority": "Priority Sector Lending Rules",
    "profit": "Profit and Loss",
    "percentage": "Percentage",
    "mixture": "Mixtures and Alligation",
    "ratio": "Ratio and Proportion",
    "compoundinterest": "Compound Interest",
    "discount": "Discount and Marked Price",
    "work": "Work and Time",
    "rubbed": "Electrostatic force",
    "transactions": "Successive Transactions",
    "tournament": "Percentage",
    "partnership": "Partnership and Profit Sharing",
    "boxes": "Profit and Loss (Comparison)",
    "combinatorics": "Combinatorics",
    "probability": "Probability",
    "charge": "Electrostatics - Charge",
    "dielectricconstant": "Electrostatics - Dielectrics",
    "electricfield": "Electrostatics - Electric Field",
    "potential": "Electrostatics - Potential",
    "charging": "Electrostatics - Charging by Friction",
    "dipole": "Magnetism - Dipole",
    "magnetic moment": "Magnetism - Magnetic Moment",
    "magnet": "Magnetism - Earth's Magnetic Field",
    "power factor": "AC Circuits - Power Factor",
    "resonance": "AC Circuits - Resonance",
    "youngsdoubleslit": "Optics - Interference",
    "polarization": "Optics - Polarization",
    "sunglasses": "Optics - Polarization Applications",
    "photocurrent": "Modern Physics - Photoelectric Effect",
    "interference": "Optics - Interference",
    "wavefront": "Optics - Wavefronts",
    "radioactive": "Nuclear Physics - Radioactivity",
    "decay": "Nuclear Physics - Gamma Decay",
    "isotones": "Nuclear Physics - Isotones",
    "electromagnetic": "Electromagnetic Waves"
}